services:
  - type: web
    name: flask-ohlc-signals
    env: python
    plan: free
    region: oregon   # or keep default, can be any Render region
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    autoDeploy: true
    envVars:
      - key: CLIENT_ID
        sync: false
      - key: ACCESS_TOKEN
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: SECRET_KEY
        sync: false
